name: final_movie_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  platform_device_id: ^1.0.1
  http: ^1.2.2
  provider: ^6.0.5
  shared_preferences: ^2.0.15
  flutter_spinkit: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/photo-not-found.jpg
  fonts:
    - family: Parkinsans
      fonts:
        - asset: assets/fonts/Parkinsans/static/Parkinsans-Bold.ttf
          weight: 700
        - asset: assets/fonts/Parkinsans/static/Parkinsans-Light.ttf
        - asset: assets/fonts/Parkinsans/static/Parkinsans-Regular.ttf
